
minima:
  skin: dark

language: ar
theme: minima
title:  ✔ مدونة

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/jekyll/jekyll" }
    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }

header_pages:
  - new.md
  - ara.md
  - RTL.md

